// Code generated by "stringer -type CarbUnitsType"; DO NOT EDIT.

package medtronic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Grams-1]
	_ = x[Exchanges-2]
}

const _CarbUnitsType_name = "GramsExchanges"

var _CarbUnitsType_index = [...]uint8{0, 5, 14}

func (i CarbUnitsType) String() string {
	i -= 1
	if i >= CarbUnitsType(len(_CarbUnitsType_index)-1) {
		return "CarbUnitsType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CarbUnitsType_name[_CarbUnitsType_index[i]:_CarbUnitsType_index[i+1]]
}
