// Code generated by "stringer -type CGMRecordType"; DO NOT EDIT.

package medtronic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CGMDataEnd-1]
	_ = x[CGMWeakSignal-2]
	_ = x[CGMCal-3]
	_ = x[CGMPacket-4]
	_ = x[CGMError-5]
	_ = x[CGMDataLow-6]
	_ = x[CGMDataHigh-7]
	_ = x[CGMTimestamp-8]
	_ = x[CGMBatteryChange-10]
	_ = x[CGMStatus-11]
	_ = x[CGMTimeChange-12]
	_ = x[CGMSync-13]
	_ = x[CGMCalBG-14]
	_ = x[CGMCalFactor-15]
	_ = x[CGMEvent10-16]
	_ = x[CGMEvent13-19]
	_ = x[CGMGlucose-32]
}

const (
	_CGMRecordType_name_0 = "CGMDataEndCGMWeakSignalCGMCalCGMPacketCGMErrorCGMDataLowCGMDataHighCGMTimestamp"
	_CGMRecordType_name_1 = "CGMBatteryChangeCGMStatusCGMTimeChangeCGMSyncCGMCalBGCGMCalFactorCGMEvent10"
	_CGMRecordType_name_2 = "CGMEvent13"
	_CGMRecordType_name_3 = "CGMGlucose"
)

var (
	_CGMRecordType_index_0 = [...]uint8{0, 10, 23, 29, 38, 46, 56, 67, 79}
	_CGMRecordType_index_1 = [...]uint8{0, 16, 25, 38, 45, 53, 65, 75}
)

func (i CGMRecordType) String() string {
	switch {
	case 1 <= i && i <= 8:
		i -= 1
		return _CGMRecordType_name_0[_CGMRecordType_index_0[i]:_CGMRecordType_index_0[i+1]]
	case 10 <= i && i <= 16:
		i -= 10
		return _CGMRecordType_name_1[_CGMRecordType_index_1[i]:_CGMRecordType_index_1[i+1]]
	case i == 19:
		return _CGMRecordType_name_2
	case i == 32:
		return _CGMRecordType_name_3
	default:
		return "CGMRecordType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
