// Code generated by "stringer -type CGMRecordType"; DO NOT EDIT.

package medtronic

import "strconv"

const (
	_CGMRecordType_name_0 = "CGMDataEndCGMWeakSignalCGMCalCGMPacketCGMErrorCGMDataLowCGMDataHighCGMTimestamp"
	_CGMRecordType_name_1 = "CGMBatteryChangeCGMStatusCGMTimeChangeCGMSyncCGMCalBGForGHCGMCalFactorCGMEvent10"
	_CGMRecordType_name_2 = "CGMEvent13"
	_CGMRecordType_name_3 = "CGMGlucose"
)

var (
	_CGMRecordType_index_0 = [...]uint8{0, 10, 23, 29, 38, 46, 56, 67, 79}
	_CGMRecordType_index_1 = [...]uint8{0, 16, 25, 38, 45, 58, 70, 80}
	_CGMRecordType_index_2 = [...]uint8{0, 10}
	_CGMRecordType_index_3 = [...]uint8{0, 10}
)

func (i CGMRecordType) String() string {
	switch {
	case 1 <= i && i <= 8:
		i -= 1
		return _CGMRecordType_name_0[_CGMRecordType_index_0[i]:_CGMRecordType_index_0[i+1]]
	case 10 <= i && i <= 16:
		i -= 10
		return _CGMRecordType_name_1[_CGMRecordType_index_1[i]:_CGMRecordType_index_1[i+1]]
	case i == 19:
		return _CGMRecordType_name_2
	case i == 32:
		return _CGMRecordType_name_3
	default:
		return "CGMRecordType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
