// Code generated by "stringer -type Command"; DO NOT EDIT.

package medtronic

import "strconv"

const _Command_name = "acknaksetClockbolussetAbsoluteTempBasalsuspendbuttonwakeupsetPercentTempBasalclockpumpIDbatteryreservoirhistoryPagecarbUnitsglucoseUnitscarbRatiosinsulinSensitivitiesmodelbasalRatesbasalPatternAbasalPatternBtempBasalglucosePageisigPagecalibrationFactorhistoryPageCountglucoseTargetssettingscgmPageCountstatusvcntrPage"

var _Command_map = map[Command]string{
	6:   _Command_name[0:3],
	21:  _Command_name[3:6],
	64:  _Command_name[6:14],
	66:  _Command_name[14:19],
	76:  _Command_name[19:39],
	77:  _Command_name[39:46],
	91:  _Command_name[46:52],
	93:  _Command_name[52:58],
	105: _Command_name[58:77],
	112: _Command_name[77:82],
	113: _Command_name[82:88],
	114: _Command_name[88:95],
	115: _Command_name[95:104],
	128: _Command_name[104:115],
	136: _Command_name[115:124],
	137: _Command_name[124:136],
	138: _Command_name[136:146],
	139: _Command_name[146:166],
	141: _Command_name[166:171],
	146: _Command_name[171:181],
	147: _Command_name[181:194],
	148: _Command_name[194:207],
	152: _Command_name[207:216],
	154: _Command_name[216:227],
	155: _Command_name[227:235],
	156: _Command_name[235:252],
	157: _Command_name[252:268],
	159: _Command_name[268:282],
	192: _Command_name[282:290],
	205: _Command_name[290:302],
	206: _Command_name[302:308],
	213: _Command_name[308:317],
}

func (i Command) String() string {
	if str, ok := _Command_map[i]; ok {
		return str
	}
	return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
}
