// Code generated by "stringer -type Command"; DO NOT EDIT.

package medtronic

import "fmt"

const _Command_name = "acknaksetClockbolussetAbsoluteTempBasalsuspendwakeupsetPercentTempBasalclockpumpIDbatteryreservoirhistoryPagerfRemoteSrfRemoteACTrfRemoteBglucoseUnitscarbRatiosinsulinSensitivitiesmodelbasalRatesbasalPatternAbasalPatternBtempBasallastHistoryPageglucoseTargetssettingsstatus"

var _Command_map = map[Command]string{
	6:   _Command_name[0:3],
	21:  _Command_name[3:6],
	64:  _Command_name[6:14],
	66:  _Command_name[14:19],
	76:  _Command_name[19:39],
	77:  _Command_name[39:46],
	93:  _Command_name[46:52],
	105: _Command_name[52:71],
	112: _Command_name[71:76],
	113: _Command_name[76:82],
	114: _Command_name[82:89],
	115: _Command_name[89:98],
	128: _Command_name[98:109],
	129: _Command_name[109:118],
	134: _Command_name[118:129],
	136: _Command_name[129:138],
	137: _Command_name[138:150],
	138: _Command_name[150:160],
	139: _Command_name[160:180],
	141: _Command_name[180:185],
	146: _Command_name[185:195],
	147: _Command_name[195:208],
	148: _Command_name[208:221],
	152: _Command_name[221:230],
	157: _Command_name[230:245],
	159: _Command_name[245:259],
	192: _Command_name[259:267],
	206: _Command_name[267:273],
}

func (i Command) String() string {
	if str, ok := _Command_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Command(%d)", i)
}
