// Code generated by "stringer -type HistoryRecordType"; DO NOT EDIT.

package medtronic

import "strconv"

const _HistoryRecordType_name = "BolusPrimeAlarmDailyTotalBasalProfileBeforeBasalProfileAfterBGCaptureSensorAlarmClearAlarmChangeBasalPatternTempBasalDurationChangeTimeNewTimeLowBatteryBatteryChangeSetAutoOffSuspendPumpResumePumpSelfTestRewindClearSettingsEnableChildBlockMaxBolusEnableRemoteMaxBasalEnableBolusWizardUnknown2EBolusWizard512UnabsorbedInsulin512ChangeBGReminderSetAlarmClockTimeTempBasalRateLowReservoirAlarmClockChangeMeterIDSensorStatusEnableMeterBGReceivedMealMarkerExerciseMarkerInsulinMarkerOtherMarkerChangeBolusWizardSetupChangeGlucoseUnitsBolusWizardSetupBolusWizardUnabsorbedInsulinSaveSettingsEnableVariableBolusChangeEasyBolusEnableBGReminderEnableAlarmClockChangeTempBasalTypeChangeAlarmTypeChangeTimeFormatChangeReservoirWarningEnableBolusReminderSetBolusReminderTimeDeleteBolusReminderTimeBolusReminderDeleteAlarmClockTimeDailyTotal515DailyTotal522DailyTotal523ChangeCarbUnitsBasalProfileStartConnectOtherDevicesChangeOtherDeviceChangeMarriageDeleteOtherDeviceEnableCaptureEvent"

var _HistoryRecordType_map = map[HistoryRecordType]string{
	1:   _HistoryRecordType_name[0:5],
	3:   _HistoryRecordType_name[5:10],
	6:   _HistoryRecordType_name[10:15],
	7:   _HistoryRecordType_name[15:25],
	8:   _HistoryRecordType_name[25:43],
	9:   _HistoryRecordType_name[43:60],
	10:  _HistoryRecordType_name[60:69],
	11:  _HistoryRecordType_name[69:80],
	12:  _HistoryRecordType_name[80:90],
	20:  _HistoryRecordType_name[90:108],
	22:  _HistoryRecordType_name[108:125],
	23:  _HistoryRecordType_name[125:135],
	24:  _HistoryRecordType_name[135:142],
	25:  _HistoryRecordType_name[142:152],
	26:  _HistoryRecordType_name[152:165],
	27:  _HistoryRecordType_name[165:175],
	30:  _HistoryRecordType_name[175:186],
	31:  _HistoryRecordType_name[186:196],
	32:  _HistoryRecordType_name[196:204],
	33:  _HistoryRecordType_name[204:210],
	34:  _HistoryRecordType_name[210:223],
	35:  _HistoryRecordType_name[223:239],
	36:  _HistoryRecordType_name[239:247],
	38:  _HistoryRecordType_name[247:259],
	44:  _HistoryRecordType_name[259:267],
	45:  _HistoryRecordType_name[267:284],
	46:  _HistoryRecordType_name[284:293],
	47:  _HistoryRecordType_name[293:307],
	48:  _HistoryRecordType_name[307:327],
	49:  _HistoryRecordType_name[327:343],
	50:  _HistoryRecordType_name[343:360],
	51:  _HistoryRecordType_name[360:373],
	52:  _HistoryRecordType_name[373:385],
	53:  _HistoryRecordType_name[385:395],
	54:  _HistoryRecordType_name[395:408],
	59:  _HistoryRecordType_name[408:420],
	60:  _HistoryRecordType_name[420:431],
	63:  _HistoryRecordType_name[431:441],
	64:  _HistoryRecordType_name[441:451],
	65:  _HistoryRecordType_name[451:465],
	66:  _HistoryRecordType_name[465:478],
	67:  _HistoryRecordType_name[478:489],
	79:  _HistoryRecordType_name[489:511],
	86:  _HistoryRecordType_name[511:529],
	90:  _HistoryRecordType_name[529:545],
	91:  _HistoryRecordType_name[545:556],
	92:  _HistoryRecordType_name[556:573],
	93:  _HistoryRecordType_name[573:585],
	94:  _HistoryRecordType_name[585:604],
	95:  _HistoryRecordType_name[604:619],
	96:  _HistoryRecordType_name[619:635],
	97:  _HistoryRecordType_name[635:651],
	98:  _HistoryRecordType_name[651:670],
	99:  _HistoryRecordType_name[670:685],
	100: _HistoryRecordType_name[685:701],
	101: _HistoryRecordType_name[701:723],
	102: _HistoryRecordType_name[723:742],
	103: _HistoryRecordType_name[742:762],
	104: _HistoryRecordType_name[762:785],
	105: _HistoryRecordType_name[785:798],
	106: _HistoryRecordType_name[798:818],
	108: _HistoryRecordType_name[818:831],
	109: _HistoryRecordType_name[831:844],
	110: _HistoryRecordType_name[844:857],
	111: _HistoryRecordType_name[857:872],
	123: _HistoryRecordType_name[872:889],
	124: _HistoryRecordType_name[889:908],
	125: _HistoryRecordType_name[908:925],
	129: _HistoryRecordType_name[925:939],
	130: _HistoryRecordType_name[939:956],
	131: _HistoryRecordType_name[956:974],
}

func (i HistoryRecordType) String() string {
	if str, ok := _HistoryRecordType_map[i]; ok {
		return str
	}
	return "HistoryRecordType(" + strconv.FormatInt(int64(i), 10) + ")"
}
