// Code generated by "stringer -type HistoryRecordType"; DO NOT EDIT

package medtronic

import "fmt"

const _HistoryRecordType_name = "BolusPrimeAlarmDailyTotalBasalProfileBeforeBasalProfileAfterBgCaptureSensorAlarmClearAlarmChangeBasalPatternTempBasalDurationChangeTimeNewTimeLowBatteryBatteryChangeSetAutoOffSuspendPumpResumePumpSelfTestRewindEnableChildBlockMaxBolusEnableRemoteMaxBasalEnableBolusWizardSetAlarmClockTimeTempBasalRateLowReservoirSensorStatusEnableMeterMealMarkerExerciseMarkerInsulinMarkerOtherMarkerChangeBolusWizardSetupChangeGlucoseUnitsBolusWizardSetupBolusWizardUnabsorbedInsulinEnableVariableBolusChangeEasyBolusEnableBgReminderEnableAlarmClockChangeTempBasalTypeChangeAlarmTypeChangeTimeFormatChangeReservoirWarningEnableBolusReminderSetBolusReminderTimeDeleteBolusReminderTimeDeleteAlarmClockTimeDailyTotal522DailyTotal523ChangeCarbUnitsBasalProfileStartConnectOtherDevicesChangeOtherDeviceDeleteOtherDeviceEnableCaptureEvent"

var _HistoryRecordType_map = map[HistoryRecordType]string{
	1:   _HistoryRecordType_name[0:5],
	3:   _HistoryRecordType_name[5:10],
	6:   _HistoryRecordType_name[10:15],
	7:   _HistoryRecordType_name[15:25],
	8:   _HistoryRecordType_name[25:43],
	9:   _HistoryRecordType_name[43:60],
	10:  _HistoryRecordType_name[60:69],
	11:  _HistoryRecordType_name[69:80],
	12:  _HistoryRecordType_name[80:90],
	20:  _HistoryRecordType_name[90:108],
	22:  _HistoryRecordType_name[108:125],
	23:  _HistoryRecordType_name[125:135],
	24:  _HistoryRecordType_name[135:142],
	25:  _HistoryRecordType_name[142:152],
	26:  _HistoryRecordType_name[152:165],
	27:  _HistoryRecordType_name[165:175],
	30:  _HistoryRecordType_name[175:186],
	31:  _HistoryRecordType_name[186:196],
	32:  _HistoryRecordType_name[196:204],
	33:  _HistoryRecordType_name[204:210],
	35:  _HistoryRecordType_name[210:226],
	36:  _HistoryRecordType_name[226:234],
	38:  _HistoryRecordType_name[234:246],
	44:  _HistoryRecordType_name[246:254],
	45:  _HistoryRecordType_name[254:271],
	50:  _HistoryRecordType_name[271:288],
	51:  _HistoryRecordType_name[288:301],
	52:  _HistoryRecordType_name[301:313],
	59:  _HistoryRecordType_name[313:325],
	60:  _HistoryRecordType_name[325:336],
	64:  _HistoryRecordType_name[336:346],
	65:  _HistoryRecordType_name[346:360],
	66:  _HistoryRecordType_name[360:373],
	67:  _HistoryRecordType_name[373:384],
	79:  _HistoryRecordType_name[384:406],
	86:  _HistoryRecordType_name[406:424],
	90:  _HistoryRecordType_name[424:440],
	91:  _HistoryRecordType_name[440:451],
	92:  _HistoryRecordType_name[451:468],
	94:  _HistoryRecordType_name[468:487],
	95:  _HistoryRecordType_name[487:502],
	96:  _HistoryRecordType_name[502:518],
	97:  _HistoryRecordType_name[518:534],
	98:  _HistoryRecordType_name[534:553],
	99:  _HistoryRecordType_name[553:568],
	100: _HistoryRecordType_name[568:584],
	101: _HistoryRecordType_name[584:606],
	102: _HistoryRecordType_name[606:625],
	103: _HistoryRecordType_name[625:645],
	104: _HistoryRecordType_name[645:668],
	106: _HistoryRecordType_name[668:688],
	109: _HistoryRecordType_name[688:701],
	110: _HistoryRecordType_name[701:714],
	111: _HistoryRecordType_name[714:729],
	123: _HistoryRecordType_name[729:746],
	124: _HistoryRecordType_name[746:765],
	129: _HistoryRecordType_name[765:782],
	130: _HistoryRecordType_name[782:799],
	131: _HistoryRecordType_name[799:817],
}

func (i HistoryRecordType) String() string {
	if str, ok := _HistoryRecordType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("HistoryRecordType(%d)", i)
}
