// Code generated by "stringer -type PumpError"; DO NOT EDIT.

package medtronic

import "fmt"

const (
	_PumpError_name_0 = "CommandRefusedMaxSettingExceeded"
	_PumpError_name_1 = "BolusInProgress"
)

var (
	_PumpError_index_0 = [...]uint8{0, 14, 32}
	_PumpError_index_1 = [...]uint8{0, 15}
)

func (i PumpError) String() string {
	switch {
	case 8 <= i && i <= 9:
		i -= 8
		return _PumpError_name_0[_PumpError_index_0[i]:_PumpError_index_0[i+1]]
	case i == 12:
		return _PumpError_name_1
	default:
		return fmt.Sprintf("PumpError(%d)", i)
	}
}
