// Code generated by "stringer -type PumpButton"; DO NOT EDIT.

package medtronic

import "strconv"

const _PumpButton_name = "BolusButtonEscButtonActButtonUpButtonDownButton"

var _PumpButton_index = [...]uint8{0, 11, 20, 29, 37, 47}

func (i PumpButton) String() string {
	if i >= PumpButton(len(_PumpButton_index)-1) {
		return "PumpButton(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PumpButton_name[_PumpButton_index[i]:_PumpButton_index[i+1]]
}
