// Code generated by "stringer -type PumpButton"; DO NOT EDIT.

package medtronic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BolusButton-0]
	_ = x[EscButton-1]
	_ = x[ActButton-2]
	_ = x[UpButton-3]
	_ = x[DownButton-4]
}

const _PumpButton_name = "BolusButtonEscButtonActButtonUpButtonDownButton"

var _PumpButton_index = [...]uint8{0, 11, 20, 29, 37, 47}

func (i PumpButton) String() string {
	if i >= PumpButton(len(_PumpButton_index)-1) {
		return "PumpButton(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PumpButton_name[_PumpButton_index[i]:_PumpButton_index[i+1]]
}
